### PR TITLE
fixed disappeared images in menu section

### PR DESCRIPTION
**Pull request by Janhvi52**
before
Screenshot (131)
after
Screenshot (132)

### CODE REVIEW

**Comment by YadnikaDabhade** [comment]
@Janhvi52  arrange them more efficiently , the space between them is not seems to be good

**Comment by Janhvi52** [comment]
> @Janhvi52 arrange them more efficiently , the space between them is not seems to be good

Screenshot (133)

arranged them properly and removed the unwanted and repeated items as well, also i reduced the size of the section
hope its fine now

**Comment by Janhvi52** [comment]
> > @Janhvi52 arrange them more efficiently , the space between them is not seems to be good
> 
> Screenshot (133)
> 
> arranged them properly and removed the unwanted and repeated items as well, also i reduced the size of the section hope its fine now

can you please check it

**Comment by YadnikaDabhade** [comment]
@Janhvi52 use some new ideas to feature them.. nothing creative work done..you only have just aligned it...do some thing more attractive

**Comment by Janhvi52** [comment]
> @Janhvi52 use some new ideas to feature them.. nothing creative work done..you only have just aligned it...do some thing more attractive

i wasn't asssigned that task so i didn't do anything extra
okay if u want i'll make another pr
kindly merge this one, i'll be doing the next pr asap

**Comment by Janhvi52** [comment]
> > @Janhvi52 use some new ideas to feature them.. nothing creative work done..you only have just aligned it...do some thing more attractive
> 
> i wasn't asssigned that task so i didn't do anything extra okay if u want i'll make another pr kindly merge this one, i'll be doing the next pr asap

hey @YadnikaDabhade ,kindly review it and merge it
i need to include this pr in my blog which i'm writing for kwoc
if u want any further changes i'll make other pr for that
thankyou!

**Pull request closed without merging**
