### PR TITLE
added contributing.md file

### LINKED ISSUE #31: add contributing guidelines
can i add contributing guidelines and thus separating readme and contributing files

### PR DESCRIPTION
**Pull request by Janhvi52**
closes #31 
you can have a look at it and merge it,thanks!

### CODE REVIEW

**Comment by YadnikaDabhade** [comment]
> closes #31 you can have a look at it and merge it,thanks!

@Janhvi52  add the screenshot of work

**Comment by Janhvi52** [comment]
> > closes #31 you can have a look at it and merge it,thanks!
> 
> @Janhvi52 add the screenshot of work

**Comment by Janhvi52** [comment]
> > closes #31 you can have a look at it and merge it,thanks!
> 
> @Janhvi52 add the screenshot of work

Screenshot (115)
Screenshot (116)
Screenshot (117)

the full file can be seen once it is merged

**Comment by Janhvi52** [comment]
> > > closes #31 you can have a look at it and merge it,thanks!
> > 
> > 
> > @Janhvi52 add the screenshot of work
> 
> Screenshot (115) Screenshot (116) Screenshot (117)
> 
> the full file can be seen once it is merged

@YadnikaDabhade can check now!

**Comment by Janhvi52** [comment]
> > > > closes #31 you can have a look at it and merge it,thanks!
> > > 
> > > 
> > > @Janhvi52 add the screenshot of work
> > 
> > 
> > Screenshot (115) Screenshot (116) Screenshot (117)
> > the full file can be seen once it is merged
> 
> @YadnikaDabhade can check now

**Pull request merged**
